# Generated by Django 3.2.17 on 2023-02-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_add_enrollment_officer_gql_query_products_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
