# Generated by Django 3.2.17 on 2023-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ceiling_type',
            field=models.CharField(blank=True, choices=[('I', 'INSUREE'), ('T', 'TREATMENT'), ('P', 'POLICY')], db_column='CeilingType', max_length=1, null=True),
        ),
    ]
