# Generated by Django 3.2.18 on 2023-05-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_insert_ceiling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='item',
            field=models.ForeignKey(db_column='ItemID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='medical.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(db_column='ProdID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productservice',
            name='product',
            field=models.ForeignKey(db_column='ProdID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productservice',
            name='service',
            field=models.ForeignKey(db_column='ServiceID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='medical.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='limitation_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='limitation_type_e',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeE', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='limitation_type_r',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeR', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='price_origin',
            field=models.CharField(blank=True, choices=[('P', 'Schema Price'), ('O', 'Providers Own Price'), ('R', 'Relative Price')], db_column='PriceOrigin', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='limitation_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationType', max_length=1),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='limitation_type_e',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeE', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='limitation_type_r',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeR', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='price_origin',
            field=models.CharField(choices=[('P', 'Schema Price'), ('O', 'Providers Own Price'), ('R', 'Relative Price')], db_column='PriceOrigin', max_length=1),
        ),
    ]

