# Generated by Django 3.2.18 on 2023-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_insert_ceiling_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
