# Generated by Django 3.2.23 on 2024-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230510_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_maximal',
            field=models.IntegerField(blank=True, db_column='Max Age', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_minimal',
            field=models.IntegerField(blank=True, db_column='Min Age', null=True),
        ),
    ]
