# Generated by Django 3.2.17 on 2026-02-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('product', '0009_auto_20240129_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='program',
            field=models.ForeignKey(db_column='program', blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_program', to='program.program'),
        )
    ]
